#optical sim for photons in the fiber
/analysis/setFileName ../ROOT/ph_test2.root
/gps/particle opticalphoton

#TDR says 425 nm light -> 2.92 eV photons
/gps/ene/type Mono
/gps/ene/mono 2.92 eV

#starting at bottom of cylinder with uniformly random direction and polarization
/gps/pos/type Point
/gps/pos/centre 0 0 -500 mm
/gps/ang/type iso
/gps/polarization 0.0 0.0 0.0


#don't need tracking since we have root file
/tracking/verbose 0

/run/beamOn 100