#test macro with a geantino for geometry checks

#i can't turn off getting a root file so just gonna scrap this one
/analysis/setFileName ../ROOT/nullTest.root

#geantino is test particle with no physical properties
/gps/particle geantino

#energy doesn't matter for geantino
/gps/energy 1 GeV

#set the position to launch geantino
#cylinder goes from -500 to +500 mm in z direction
/gps/pos/type Point
/gps/pos/centre 0 0 0 mm


# Shoot along +x to check cladding and core
/gps/direction 1 0 0

#gives step by step tracking
/tracking/verbose 1

#tells how many events we want to simulate
/run/beamOn 1